#!/usr/local/bin/python3
from boto3.session import Session
from botocore.exceptions import ProfileNotFound,ClientError
import requests
import os
import argparse
import configparser
import sys

# Configurations

parser = argparse.ArgumentParser(description='Add your current public ip into AWS security group')
parser.add_argument('profile_names', metavar='Profile Names', nargs='+', help='ipadd profile name(s)')
args = parser.parse_args()

config_file = "{}/.aws_ipadd/aws_ipadd".format(os.environ['HOME'])
public_ip = requests.get('https://checkip.amazonaws.com').text.strip() + '/32'

# Defining helper functions

def allow_ip_permission(session, security_group_id, ip, data):
    session.authorize_security_group_ingress(
        GroupId=security_group_id,
        IpPermissions=[
            {
                'FromPort': data["port"],
                'ToPort': data["port"],
                'IpProtocol': data["protocol"],
                'IpRanges': [{'CidrIp': ip, 'Description': data["rule_name"]}]
            }])

def revoke_ip_permission(session, security_group_id, ip, data):
    session.revoke_security_group_ingress(
        GroupId=security_group_id,
        IpPermissions=[
            {
                'FromPort': data["port"],
                'ToPort': data["port"],
                'IpProtocol': data["protocol"],
                'IpRanges': [{'CidrIp': ip}]
            }])

def create_rule(session, security_group_id, public_ip, data):
    try:
        allow_ip_permission(session, security_group_id, public_ip, data)
        print("Successful! Your IP {} and Port {} is whitelisted.".format(public_ip, data["port"]))
    except Exception as error:
        error = str(error)
        print(error[error.index(':') + 2:])

# Loop over profile names
for profile_name in args.profile_names:
    # Reading file for config
    config = configparser.ConfigParser()
    config.sections()
    config.read(config_file)

    # Check if config exists for the profile name
    if not profile_name in config:
        print("Profile_name \"" + profile_name + "\" doesn't exist, please check \"" + config_file + "\" file.")
        continue
    
    # Initialising required variables
    config = config[profile_name]
    rule_name = config['rule_name']
    port = int(config['port'])
    protocol = config['protocol'] or 'tcp'
    security_group_id = config['security_group_id']
    aws_profile = config['aws_profile']
    region_name = config['region_name']

    session = Session(profile_name=aws_profile,region_name=region_name)
    session = session.client('ec2')

    try:
        security_group = session.describe_security_groups(GroupIds=[security_group_id])
    except ClientError as error:
        print(error)
        sys.exit()

    try:
        security_group_rules = security_group['SecurityGroups'][0]['IpPermissions']
    except ClientError as error:
        print(error)
        sys.exit()

    security_group_rule = [security_group_rule for security_group_rule in security_group_rules if 'FromPort' in security_group_rule and security_group_rule['FromPort'] == port]

    current_public_ip = [ip for ip in security_group_rule[0]['IpRanges'] if ip['CidrIp'] != public_ip]
    security_group_rule_name = [sg_rule_name for sg_rule_name in current_public_ip if 'Description' in sg_rule_name and sg_rule_name['Description'] == rule_name]
    
    # Create rule if rule not defined
    if len(security_group_rule) == 0:
        create_rule(session, security_group_id, public_ip, {"port": port, "protocol": protocol, "rule_name": rule_name})
        sys.exit()

    # Check rule name
    if len(security_group_rule_name) != 0:
        print("Modifying existing rule...")
        exist_ip = security_group_rule_name[0]['CidrIp']

        try:
            print("Removing old whitelisted IP '{}'.".format(exist_ip))
            revoke_ip_permission(session, security_group_id, exist_ip, {"port": port, "protocol": protocol, "rule_name": rule_name})
            print("Whitelisting new IP '{}'.".format(public_ip))
            allow_ip_permission(session, security_group_id, public_ip, {"port": port, "protocol": protocol, "rule_name": rule_name})
            print("Rule successfully updated!")
        except Exception as error:
            error = str(error)
            print(error[error.index(':') + 2:])
    else:
        create_rule(session, security_group_id, public_ip, {"port": port, "protocol": protocol, "rule_name": rule_name})