name: Build and Release aws_ipadd

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run:  make build

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aws_ipadd-artifacts
          path: dist/

  release:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: aws_ipadd-binary

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/aws_ipadd_darwin_amd64.tar.gz
            dist/aws_ipadd_darwin_arm64.tar.gz
            dist/aws_ipadd_linux_amd64.tar.gz
            dist/aws_ipadd_linux_arm64.tar.gz
          name: "Release ${{ github.ref_name }}"
          tag_name: "${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}